import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { ShieldCheck, AlertCircle } from "lucide-react";

interface CodeExplanationModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
  onFailure: () => void;
  codeSnippet: string;
}

export const CodeExplanationModal = ({
  isOpen,
  onClose,
  onSuccess,
  onFailure,
  codeSnippet,
}: CodeExplanationModalProps) => {
  const [selectedAnswer, setSelectedAnswer] = useState<string | null>(null);
  const [isSubmitted, setIsSubmitted] = useState(false);
  
  // In a real app, these would be generated by AI based on codeSnippet
  const questions = [
    {
      id: "q1",
      question: "What is the primary purpose of this code block?",
      options: [
        { id: "a", text: "It handles data validation and error formatting." },
        { id: "b", text: "It manages state for the user interface." },
        { id: "c", text: "It performs an optimized database query." },
      ],
      correct: "a",
    }
  ];

  const handleSubmit = () => {
    setIsSubmitted(true);
    if (selectedAnswer === questions[0].correct) {
      setTimeout(() => {
        onSuccess();
        onClose();
        setIsSubmitted(false);
        setSelectedAnswer(null);
      }, 1500);
    } else {
      setTimeout(() => {
        onFailure();
        onClose();
        setIsSubmitted(false);
        setSelectedAnswer(null);
      }, 1500);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-md bg-card border-accent/20">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <ShieldCheck className="w-5 h-5 text-accent" />
            Proof of Work Verification
          </DialogTitle>
          <DialogDescription>
            You must explain your work to confirm skill transfer. Fail? Task resets.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          <div className="bg-muted/50 p-3 rounded-md border border-border font-mono text-[10px] overflow-x-auto max-h-32">
            <pre>{codeSnippet || "// No code snippet selected"}</pre>
          </div>

          <div className="space-y-3">
            <p className="text-sm font-medium">{questions[0].question}</p>
            <RadioGroup onValueChange={setSelectedAnswer} value={selectedAnswer || ""}>
              {questions[0].options.map((opt) => (
                <div key={opt.id} className="flex items-center space-x-2 p-2 rounded hover:bg-secondary/20 transition-colors">
                  <RadioGroupItem value={opt.id} id={opt.id} />
                  <Label htmlFor={opt.id} className="text-xs cursor-pointer flex-1">
                    {opt.text}
                  </Label>
                </div>
              ))}
            </RadioGroup>
          </div>
        </div>

        <DialogFooter>
          <Button 
            onClick={handleSubmit} 
            disabled={!selectedAnswer || isSubmitted}
            className="w-full bg-accent hover:bg-accent/90"
          >
            {isSubmitted ? (
               selectedAnswer === questions[0].correct ? "Verification Passed!" : "Verification Failed!"
            ) : "Submit Explanation"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
